export const ROUTES = {
	HomePage: '/',
	ProfilePage: '/profile',
	SignInPage: '/signin',
	SignUpPage: '/signup',
	ResetPasswordPage: '/resetpass',
	NewPasswordPage: '/resetpass/newpass',
	AdminPage: '/admin',
	ClientManagement: '/admin/client',
	AnnouncementForm: '/admin/announcment',
	EventForm: '/admin/event',
	SystemSetting: '/admin/setting',
	RoomCreation: '/admin/roomcreate',
	HotelCreation: '/admin/hotelcreate',
	ReportSelection: '/admin/report',
	OccupancyIncomeReport: '/admin/report/report-occupancy-income',
	DailyOcupancyReport: '/admin/report/report-daily-occupancy',
	ReservationStatusReport: '/admin/report/report-reservation-status',
	ClientHistoryReport: '/admin/report/report-client-history',
	RoomsListPage: '/hotel/:hotelId/rooms',
	ReservationsPage: '/user/:userId/reservations',
	ReservationTimesPage: '/rooms/:roomId/reservation-times',
	InboxPage: '/inbox',
};
